services:
  nginx:
    image: nginx:latest
    ports:
      - 127.0.0.1:8081:80
    volumes:
      - ./docker/nginx/conf.d/nginx.${APP_ENV}.conf:/etc/nginx/conf.d/default.conf
      - ./public:/app/public
  php:
    build:
      context: .
      target: symfony_php
    volumes:
      - ./var:/app/var:rw
      - ./public:/app/public
    ports:
      - 127.0.0.1:9000:9000
    env_file:
      - .env.local
  database:
    image: postgres:18
    hostname: postgres
    volumes:
      - ./.data:/var/lib/postgresql
    ports:
      - 127.0.0.1:5432:5432
    env_file:
      - .env.local
